
// This file has been generated by the GUI designer. Do not modify.
namespace NuevoModulo
{
	public partial class wConfigForm
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NuevoModulo.wConfigForm
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NuevoModulo.wConfigForm";
			// Container child NuevoModulo.wConfigForm.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::NuevoModulo.Tr.Catalog.GetString ("Configuración");
			this.alignment1.Add (this.label1);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
